// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo-L9rJyR9SOlI9piaoS7wMw-klg0Uxtw',
    appId: '1:1070492584469:web:737fc437625067b52d9c1c',
    messagingSenderId: '1070492584469',
    projectId: 'sports-calendar-sync-a4564',
    authDomain: 'sports-calendar-sync-a4564.firebaseapp.com',
    storageBucket: 'sports-calendar-sync-a4564.firebasestorage.app',
    measurementId: 'G-7WZN17RFDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR4edl9E2HfjcGShrCZJtop5dTzWXxa7Y',
    appId: '1:1070492584469:android:53a28feb534909c42d9c1c',
    messagingSenderId: '1070492584469',
    projectId: 'sports-calendar-sync-a4564',
    storageBucket: 'sports-calendar-sync-a4564.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz0ssvTbtEDhZNIuAkbOepaXIlnqsNJYY',
    appId: '1:1070492584469:ios:5b1f8ce3497accb42d9c1c',
    messagingSenderId: '1070492584469',
    projectId: 'sports-calendar-sync-a4564',
    storageBucket: 'sports-calendar-sync-a4564.firebasestorage.app',
    iosBundleId: 'com.example.sportsCalendarSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz0ssvTbtEDhZNIuAkbOepaXIlnqsNJYY',
    appId: '1:1070492584469:ios:5b1f8ce3497accb42d9c1c',
    messagingSenderId: '1070492584469',
    projectId: 'sports-calendar-sync-a4564',
    storageBucket: 'sports-calendar-sync-a4564.firebasestorage.app',
    iosBundleId: 'com.example.sportsCalendarSync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo-L9rJyR9SOlI9piaoS7wMw-klg0Uxtw',
    appId: '1:1070492584469:web:8c1cfae889ff08f92d9c1c',
    messagingSenderId: '1070492584469',
    projectId: 'sports-calendar-sync-a4564',
    authDomain: 'sports-calendar-sync-a4564.firebaseapp.com',
    storageBucket: 'sports-calendar-sync-a4564.firebasestorage.app',
    measurementId: 'G-HP0MQ2DP2C',
  );
}
